
package com.vhl.desafiotecnico.wsdl;

import java.util.List;
import javax.activation.DataHandler;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SeloService", targetNamespace = "http://www.tjsc.jus.br/selo")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SeloService {


    /**
     * 
     * @return
     *     returns java.util.List<com.vhl.desafiotecnico.wsdl.SituacaoTitulo>
     */
    @WebMethod
    @WebResult(name = "situacoesDeTitulo", targetNamespace = "")
    @RequestWrapper(localName = "getSituacoesDeTitulo", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetSituacoesDeTitulo")
    @ResponseWrapper(localName = "getSituacoesDeTituloResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetSituacoesDeTituloResponse")
    public List<SituacaoTitulo> getSituacoesDeTitulo();

    /**
     * 
     * @return
     *     returns java.util.List<com.vhl.desafiotecnico.wsdl.TipoCobranca>
     */
    @WebMethod
    @WebResult(name = "tiposDeCobranca", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeCobranca", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetTiposDeCobranca")
    @ResponseWrapper(localName = "getTiposDeCobrancaResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetTiposDeCobrancaResponse")
    public List<TipoCobranca> getTiposDeCobranca();

    /**
     * 
     * @return
     *     returns java.util.List<com.vhl.desafiotecnico.wsdl.TipoCobranca20>
     */
    @WebMethod
    @WebResult(name = "tiposDeCobranca20", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeCobranca20", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetTiposDeCobranca20")
    @ResponseWrapper(localName = "getTiposDeCobranca20Response", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetTiposDeCobranca20Response")
    public List<TipoCobranca20> getTiposDeCobranca20();

    /**
     * 
     * @param pass
     * @param user
     * @return
     *     returns java.util.List<com.vhl.desafiotecnico.wsdl.JuizPaz>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "juizesDePaz", targetNamespace = "")
    @RequestWrapper(localName = "getJuizesDePaz", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetJuizesDePaz")
    @ResponseWrapper(localName = "getJuizesDePazResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetJuizesDePazResponse")
    public List<JuizPaz> getJuizesDePaz(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass)
        throws Exception_Exception
    ;

    /**
     * 
     * @param pass
     * @param nupedido
     * @param user
     * @param isento
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "selosPedido", targetNamespace = "")
    @RequestWrapper(localName = "getSelosPedido", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetSelosPedido")
    @ResponseWrapper(localName = "getSelosPedidoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetSelosPedidoResponse")
    public byte[] getSelosPedido(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass,
        @WebParam(name = "nupedido", targetNamespace = "")
        Long nupedido,
        @WebParam(name = "isento", targetNamespace = "")
        Boolean isento)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.vhl.desafiotecnico.wsdl.TipoSubestabelecimento>
     */
    @WebMethod
    @WebResult(name = "tiposDeSubestabelecimento", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeSubestabelecimento", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetTiposDeSubestabelecimento")
    @ResponseWrapper(localName = "getTiposDeSubestabelecimentoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetTiposDeSubestabelecimentoResponse")
    public List<TipoSubestabelecimento> getTiposDeSubestabelecimento();

    /**
     * 
     * @return
     *     returns java.util.List<com.vhl.desafiotecnico.wsdl.Banco>
     */
    @WebMethod
    @WebResult(name = "bancos", targetNamespace = "")
    @RequestWrapper(localName = "getBancos", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetBancos")
    @ResponseWrapper(localName = "getBancosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetBancosResponse")
    public List<Banco> getBancos();

    /**
     * 
     * @param pass
     * @param user
     * @return
     *     returns java.util.List<com.vhl.desafiotecnico.wsdl.CartorioLivro20>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "cartorioLivros20", targetNamespace = "")
    @RequestWrapper(localName = "getCartorioLivros20", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetCartorioLivros20")
    @ResponseWrapper(localName = "getCartorioLivros20Response", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetCartorioLivros20Response")
    public List<CartorioLivro20> getCartorioLivros20(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.vhl.desafiotecnico.wsdl.Etnia>
     */
    @WebMethod
    @WebResult(name = "etnias", targetNamespace = "")
    @RequestWrapper(localName = "getEtnias", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetEtnias")
    @ResponseWrapper(localName = "getEtniasResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetEtniasResponse")
    public List<Etnia> getEtnias();

    /**
     * 
     * @return
     *     returns java.util.List<com.vhl.desafiotecnico.wsdl.TipoRegistroAverbacao>
     */
    @WebMethod
    @WebResult(name = "tiposDeRegistroDeAverbacao", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeRegistroDeAverbacao", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetTiposDeRegistroDeAverbacao")
    @ResponseWrapper(localName = "getTiposDeRegistroDeAverbacaoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetTiposDeRegistroDeAverbacaoResponse")
    public List<TipoRegistroAverbacao> getTiposDeRegistroDeAverbacao();

    /**
     * 
     * @return
     *     returns java.util.List<com.vhl.desafiotecnico.wsdl.TipoTelefone>
     */
    @WebMethod
    @WebResult(name = "tiposDeTelefone", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeTelefone", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetTiposDeTelefone")
    @ResponseWrapper(localName = "getTiposDeTelefoneResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetTiposDeTelefoneResponse")
    public List<TipoTelefone> getTiposDeTelefone();

    /**
     * 
     * @return
     *     returns java.util.List<com.vhl.desafiotecnico.wsdl.TipoTestamento>
     */
    @WebMethod
    @WebResult(name = "tiposDeTestamento", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeTestamento", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetTiposDeTestamento")
    @ResponseWrapper(localName = "getTiposDeTestamentoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetTiposDeTestamentoResponse")
    public List<TipoTestamento> getTiposDeTestamento();

    /**
     * 
     * @return
     *     returns java.util.List<com.vhl.desafiotecnico.wsdl.Comarca>
     */
    @WebMethod
    @WebResult(name = "comarcas", targetNamespace = "")
    @RequestWrapper(localName = "getComarcas", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetComarcas")
    @ResponseWrapper(localName = "getComarcasResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetComarcasResponse")
    public List<Comarca> getComarcas();

    /**
     * 
     * @return
     *     returns java.util.List<com.vhl.desafiotecnico.wsdl.TipoDocumento>
     */
    @WebMethod
    @WebResult(name = "tiposDeDocumento", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeDocumento", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetTiposDeDocumento")
    @ResponseWrapper(localName = "getTiposDeDocumentoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetTiposDeDocumentoResponse")
    public List<TipoDocumento> getTiposDeDocumento();

    /**
     * 
     * @return
     *     returns java.util.List<com.vhl.desafiotecnico.wsdl.TipoAto>
     */
    @WebMethod
    @WebResult(name = "tiposDeAto", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeAto", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetTiposDeAto")
    @ResponseWrapper(localName = "getTiposDeAtoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetTiposDeAtoResponse")
    public List<TipoAto> getTiposDeAto();

    /**
     * 
     * @return
     *     returns java.util.List<com.vhl.desafiotecnico.wsdl.TipoSelo>
     */
    @WebMethod
    @WebResult(name = "tiposDeSelo", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeSelo", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetTiposDeSelo")
    @ResponseWrapper(localName = "getTiposDeSeloResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetTiposDeSeloResponse")
    public List<TipoSelo> getTiposDeSelo();

    /**
     * 
     * @return
     *     returns java.util.List<com.vhl.desafiotecnico.wsdl.Moeda>
     */
    @WebMethod
    @WebResult(name = "moedas", targetNamespace = "")
    @RequestWrapper(localName = "getMoedas", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetMoedas")
    @ResponseWrapper(localName = "getMoedasResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetMoedasResponse")
    public List<Moeda> getMoedas();

    /**
     * 
     * @return
     *     returns java.util.List<com.vhl.desafiotecnico.wsdl.MotivoProtesto>
     */
    @WebMethod
    @WebResult(name = "motivosDeProtesto", targetNamespace = "")
    @RequestWrapper(localName = "getMotivosDeProtesto", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetMotivosDeProtesto")
    @ResponseWrapper(localName = "getMotivosDeProtestoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetMotivosDeProtestoResponse")
    public List<MotivoProtesto> getMotivosDeProtesto();

    /**
     * 
     * @return
     *     returns java.util.List<com.vhl.desafiotecnico.wsdl.EstadoCivil>
     */
    @WebMethod
    @WebResult(name = "estadosCivis", targetNamespace = "")
    @RequestWrapper(localName = "getEstadosCivis", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetEstadosCivis")
    @ResponseWrapper(localName = "getEstadosCivisResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetEstadosCivisResponse")
    public List<EstadoCivil> getEstadosCivis();

    /**
     * 
     * @return
     *     returns java.util.List<com.vhl.desafiotecnico.wsdl.Pais>
     */
    @WebMethod
    @WebResult(name = "paises", targetNamespace = "")
    @RequestWrapper(localName = "getPaises", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetPaises")
    @ResponseWrapper(localName = "getPaisesResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetPaisesResponse")
    public List<Pais> getPaises();

    /**
     * 
     * @return
     *     returns java.util.List<com.vhl.desafiotecnico.wsdl.Escolaridade>
     */
    @WebMethod
    @WebResult(name = "escolaridades", targetNamespace = "")
    @RequestWrapper(localName = "getEscolaridades", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetEscolaridades")
    @ResponseWrapper(localName = "getEscolaridadesResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetEscolaridadesResponse")
    public List<Escolaridade> getEscolaridades();

    /**
     * 
     * @param messageIDtransmissao
     * @param pass
     * @param user
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "reciboTSRarmazenado", targetNamespace = "")
    @RequestWrapper(localName = "verificaTransmissao", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.VerificaTransmissao")
    @ResponseWrapper(localName = "verificaTransmissaoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.VerificaTransmissaoResponse")
    public byte[] verificaTransmissao(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass,
        @WebParam(name = "messageIDtransmissao", targetNamespace = "")
        Integer messageIDtransmissao)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.vhl.desafiotecnico.wsdl.EspecieTitulo>
     */
    @WebMethod
    @WebResult(name = "especiesDeTitulo", targetNamespace = "")
    @RequestWrapper(localName = "getEspeciesDeTitulo", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetEspeciesDeTitulo")
    @ResponseWrapper(localName = "getEspeciesDeTituloResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetEspeciesDeTituloResponse")
    public List<EspecieTitulo> getEspeciesDeTitulo();

    /**
     * 
     * @param pass
     * @param nupedido
     * @param user
     * @param isento
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "selosPedidoCompactados", targetNamespace = "")
    @RequestWrapper(localName = "getSelosPedidoCompactados", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetSelosPedidoCompactados")
    @ResponseWrapper(localName = "getSelosPedidoCompactadosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetSelosPedidoCompactadosResponse")
    public byte[] getSelosPedidoCompactados(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass,
        @WebParam(name = "nupedido", targetNamespace = "")
        Long nupedido,
        @WebParam(name = "isento", targetNamespace = "")
        Boolean isento)
        throws Exception_Exception
    ;

    /**
     * 
     * @param pass
     * @param user
     * @return
     *     returns java.util.List<com.vhl.desafiotecnico.wsdl.CartorioServentuario20>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "cartorioServentuarios20", targetNamespace = "")
    @RequestWrapper(localName = "getCartorioServentuarios20", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetCartorioServentuarios20")
    @ResponseWrapper(localName = "getCartorioServentuarios20Response", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetCartorioServentuarios20Response")
    public List<CartorioServentuario20> getCartorioServentuarios20(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.vhl.desafiotecnico.wsdl.MotivoCancelProtesto>
     */
    @WebMethod
    @WebResult(name = "motivosDeCancelamentoDoProtesto", targetNamespace = "")
    @RequestWrapper(localName = "getMotivosDeCancelamentoDoProtesto", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetMotivosDeCancelamentoDoProtesto")
    @ResponseWrapper(localName = "getMotivosDeCancelamentoDoProtestoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetMotivosDeCancelamentoDoProtestoResponse")
    public List<MotivoCancelProtesto> getMotivosDeCancelamentoDoProtesto();

    /**
     * 
     * @param recibo
     * @param pass
     * @param user
     * @return
     *     returns com.vhl.desafiotecnico.wsdl.ReciboProtocolo
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "reciboDecodificado", targetNamespace = "")
    @RequestWrapper(localName = "decodificaRecibo", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.DecodificaRecibo")
    @ResponseWrapper(localName = "decodificaReciboResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.DecodificaReciboResponse")
    public ReciboProtocolo decodificaRecibo(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass,
        @WebParam(name = "recibo", targetNamespace = "")
        DataHandler recibo)
        throws Exception_Exception
    ;

    /**
     * 
     * @param pass
     * @param user
     * @return
     *     returns java.util.List<com.vhl.desafiotecnico.wsdl.JuizPaz20>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "juizesDePaz20", targetNamespace = "")
    @RequestWrapper(localName = "getJuizesDePaz20", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetJuizesDePaz20")
    @ResponseWrapper(localName = "getJuizesDePaz20Response", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetJuizesDePaz20Response")
    public List<JuizPaz20> getJuizesDePaz20(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.vhl.desafiotecnico.wsdl.TipoServentuario>
     */
    @WebMethod
    @WebResult(name = "tiposDeServentuario", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeServentuario", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetTiposDeServentuario")
    @ResponseWrapper(localName = "getTiposDeServentuarioResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetTiposDeServentuarioResponse")
    public List<TipoServentuario> getTiposDeServentuario();

    /**
     * 
     * @return
     *     returns java.util.List<com.vhl.desafiotecnico.wsdl.ComarcaMunicipio>
     */
    @WebMethod
    @WebResult(name = "comarcasmunicipios", targetNamespace = "")
    @RequestWrapper(localName = "getComarcasMunicipios", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetComarcasMunicipios")
    @ResponseWrapper(localName = "getComarcasMunicipiosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetComarcasMunicipiosResponse")
    public List<ComarcaMunicipio> getComarcasMunicipios();

    /**
     * 
     * @param pass
     * @param user
     * @return
     *     returns java.util.List<com.vhl.desafiotecnico.wsdl.CartorioServentuario>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "cartorioServentuarios", targetNamespace = "")
    @RequestWrapper(localName = "getCartorioServentuarios", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetCartorioServentuarios")
    @ResponseWrapper(localName = "getCartorioServentuariosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetCartorioServentuariosResponse")
    public List<CartorioServentuario> getCartorioServentuarios(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass)
        throws Exception_Exception
    ;

    /**
     * 
     * @param pass
     * @param user
     * @return
     *     returns java.util.List<com.vhl.desafiotecnico.wsdl.CartorioLivro>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "cartorioLivros", targetNamespace = "")
    @RequestWrapper(localName = "getCartorioLivros", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetCartorioLivros")
    @ResponseWrapper(localName = "getCartorioLivrosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetCartorioLivrosResponse")
    public List<CartorioLivro> getCartorioLivros(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.vhl.desafiotecnico.wsdl.Profissao>
     */
    @WebMethod
    @WebResult(name = "profissoes", targetNamespace = "")
    @RequestWrapper(localName = "getProfissoes", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetProfissoes")
    @ResponseWrapper(localName = "getProfissoesResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetProfissoesResponse")
    public List<Profissao> getProfissoes();

    /**
     * 
     * @return
     *     returns java.util.List<com.vhl.desafiotecnico.wsdl.Cartorio>
     */
    @WebMethod
    @WebResult(name = "cartorios", targetNamespace = "")
    @RequestWrapper(localName = "getCartorios", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetCartorios")
    @ResponseWrapper(localName = "getCartoriosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetCartoriosResponse")
    public List<Cartorio> getCartorios();

    /**
     * 
     * @return
     *     returns java.util.List<com.vhl.desafiotecnico.wsdl.Municipio>
     */
    @WebMethod
    @WebResult(name = "municipios", targetNamespace = "")
    @RequestWrapper(localName = "getMunicipios", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetMunicipios")
    @ResponseWrapper(localName = "getMunicipiosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetMunicipiosResponse")
    public List<Municipio> getMunicipios();

    /**
     * 
     * @param pass
     * @param user
     * @return
     *     returns int
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "numeroSelosLiberados", targetNamespace = "")
    @RequestWrapper(localName = "redisponibilizaUltimaTransmissaoSelos", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.RedisponibilizaUltimaTransmissaoSelos")
    @ResponseWrapper(localName = "redisponibilizaUltimaTransmissaoSelosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.RedisponibilizaUltimaTransmissaoSelosResponse")
    public int redisponibilizaUltimaTransmissaoSelos(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass)
        throws Exception_Exception
    ;

    /**
     * 
     * @param pass
     * @param user
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "selosCompactados", targetNamespace = "")
    @RequestWrapper(localName = "getSelosCompactados", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetSelosCompactados")
    @ResponseWrapper(localName = "getSelosCompactadosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetSelosCompactadosResponse")
    public byte[] getSelosCompactados(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.vhl.desafiotecnico.wsdl.TipoEndereco>
     */
    @WebMethod
    @WebResult(name = "tiposDeEndereco", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeEndereco", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetTiposDeEndereco")
    @ResponseWrapper(localName = "getTiposDeEnderecoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetTiposDeEnderecoResponse")
    public List<TipoEndereco> getTiposDeEndereco();

    /**
     * 
     * @param pass
     * @param user
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "selosAssinados", targetNamespace = "")
    @RequestWrapper(localName = "getSelos", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetSelos")
    @ResponseWrapper(localName = "getSelosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetSelosResponse")
    public byte[] getSelos(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.vhl.desafiotecnico.wsdl.TipoAto20>
     */
    @WebMethod
    @WebResult(name = "tiposDeAto20", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeAto20", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetTiposDeAto20")
    @ResponseWrapper(localName = "getTiposDeAto20Response", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetTiposDeAto20Response")
    public List<TipoAto20> getTiposDeAto20();

    /**
     * 
     * @return
     *     returns java.util.List<com.vhl.desafiotecnico.wsdl.TipoProcuracao>
     */
    @WebMethod
    @WebResult(name = "tiposDeProcuracao", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeProcuracao", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetTiposDeProcuracao")
    @ResponseWrapper(localName = "getTiposDeProcuracaoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetTiposDeProcuracaoResponse")
    public List<TipoProcuracao> getTiposDeProcuracao();

    /**
     * 
     * @return
     *     returns java.util.List<com.vhl.desafiotecnico.wsdl.TipoEndosso>
     */
    @WebMethod
    @WebResult(name = "tiposDeEndosso", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeEndosso", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetTiposDeEndosso")
    @ResponseWrapper(localName = "getTiposDeEndossoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetTiposDeEndossoResponse")
    public List<TipoEndosso> getTiposDeEndosso();

    /**
     * 
     * @return
     *     returns java.util.List<com.vhl.desafiotecnico.wsdl.EnteDeclaradoUtilidadePublicaEstadual>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "entesDeclaradosUtilidadePublicaEstadual", targetNamespace = "")
    @RequestWrapper(localName = "getEntesDeclaradosUtilidadePublicaEstadual", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetEntesDeclaradosUtilidadePublicaEstadual")
    @ResponseWrapper(localName = "getEntesDeclaradosUtilidadePublicaEstadualResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetEntesDeclaradosUtilidadePublicaEstadualResponse")
    public List<EnteDeclaradoUtilidadePublicaEstadual> getEntesDeclaradosUtilidadePublicaEstadual()
        throws Exception_Exception
    ;

    /**
     * 
     * @param pass
     * @param arquivo
     * @param user
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "reciboTSR", targetNamespace = "")
    @RequestWrapper(localName = "putAtos", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.PutAtos")
    @ResponseWrapper(localName = "putAtosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.PutAtosResponse")
    public byte[] putAtos(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass,
        @WebParam(name = "arquivo", targetNamespace = "")
        DataHandler arquivo)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.vhl.desafiotecnico.wsdl.Estado>
     */
    @WebMethod
    @WebResult(name = "estados", targetNamespace = "")
    @RequestWrapper(localName = "getEstados", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetEstados")
    @ResponseWrapper(localName = "getEstadosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetEstadosResponse")
    public List<Estado> getEstados();

    /**
     * 
     * @return
     *     returns java.util.List<com.vhl.desafiotecnico.wsdl.FormaPagamento>
     */
    @WebMethod
    @WebResult(name = "formasDePagamento", targetNamespace = "")
    @RequestWrapper(localName = "getFormasDePagamento", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetFormasDePagamento")
    @ResponseWrapper(localName = "getFormasDePagamentoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetFormasDePagamentoResponse")
    public List<FormaPagamento> getFormasDePagamento();

    /**
     * 
     * @return
     *     returns java.util.List<com.vhl.desafiotecnico.wsdl.TipoEmail>
     */
    @WebMethod
    @WebResult(name = "tiposDeEmail", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeEmail", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetTiposDeEmail")
    @ResponseWrapper(localName = "getTiposDeEmailResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.vhl.desafiotecnico.wsdl.GetTiposDeEmailResponse")
    public List<TipoEmail> getTiposDeEmail();

}
